### ISSUE TITLE
在导入 /v2/api-docs的url时报错：

### ISSUE THREAD

**Issue by zaojingyoutu** [JingheLee/swagger2#1]
在导入 /v2/api-docs的url时报错：    
raise Exception('The model is incomplete. Please adjust the deep value of the swagger object.')
Exception: The model is incomplete. Please adjust the deep value of the swagger object.

当注释后：![image](https://user-images.githubusercontent.com/62125751/216242707-d9dc439f-2e0c-427a-b891-d268bb6edc48.png)

解析正常了，作者这段代码时什么意思？

**Comment by WALL-1** [comment]
比较一个集合是否包含另一个集合，你可以看看python的set对象api

**Comment by WALL-1** [comment]
上面的报错是因为接口模型嵌套深度太深了，你修改一下deep参数的默认值就可以。

**Comment by zaojingyoutu** [comment]
修改过修改为100还是有问题，还有些其它问题（比如有的类型没有，有的参数可能没有），我本地修改代码后能用了
